// Parent side of the journey sandbox (02-architecture §5.2/§7). Writes the
// user's spec body into a temp ES module, then spawns runner-harness.js in a
// SEPARATE node process with:
//   - a clean env (no platform env vars — no DATABASE_URL/REDIS_URL/
//     ENCRYPTION_KEY; only what Chromium needs to start),
//   - a hard SIGKILL backstop shortly after timeout_ms (the harness's soft
//     timeout fires first for await-hangs; the backstop catches event-loop
//     blockers like while(true){}),
//   - a 10 MB stdout cap.
// The child reports one marked JSON line on stdout (see protocol.ts).
import { spawn } from 'node:child_process';
import { promises as fs, existsSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { RESULT_MARKER, type HarnessConfig, type HarnessResult } from './protocol.js';

const STDOUT_CAP_BYTES = 10 * 1024 * 1024; // 10 MB
/**
 * Grace between the harness soft timeout and the parent SIGKILL backstop.
 *
 * Must cover the harness's whole post-timeout path: capture a screenshot, then
 * stop tracing and zip the trace, which bundles DOM snapshots and per-action
 * screenshots and is not fast. At 3s a loaded machine SIGKILLed the child
 * mid-write, losing exactly the artifacts a hung journey needs for debugging.
 */
const HARD_KILL_GRACE_MS = 10_000;

export interface SandboxInput {
  /** The journey spec body (statements using page/context/expect). */
  specSource: string;
  timeoutMs: number;
  /** Absolute dir for failure artifacts; null discards them (dry-run). */
  artifactsDir: string | null;
}

export interface SandboxOutcome extends HarnessResult {
  /** True when the parent had to SIGKILL the child (event-loop blocker). */
  hardKilled: boolean;
}

/**
 * Locate the built harness. The worker's own code may run from src (tsx/tests)
 * or bundled dist; the harness is always the *built* file so the child runs
 * plain node with no loader.
 */
export function resolveHarnessPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.resolve(here, 'runner-harness.js'), // running from dist/sandbox
    path.resolve(here, 'sandbox/runner-harness.js'), // bundled dist/index.js
    path.resolve(here, '../../dist/sandbox/runner-harness.js'), // running from src/sandbox
    path.resolve(here, '../dist/sandbox/runner-harness.js'), // src one level up
  ];
  const found = candidates.find((c) => existsSync(c));
  if (!found) {
    throw new Error(`runner-harness.js not found (build @vyzus/worker first). Tried:\n${candidates.join('\n')}`);
  }
  return found;
}

/** Only what the child needs to start node + Chromium. Nothing platform. */
function cleanChildEnv(): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {};
  // Note: VYZUS_CHROMIUM_EXECUTABLE is a browser path, not a platform secret,
  // so forwarding it does not weaken the sandbox (DATABASE_URL etc. stay excluded).
  for (const key of [
    'PATH',
    'HOME',
    'TMPDIR',
    'PLAYWRIGHT_BROWSERS_PATH',
    'XDG_CACHE_HOME',
    'VYZUS_CHROMIUM_EXECUTABLE',
  ] as const) {
    const value = process.env[key];
    if (value !== undefined) env[key] = value;
  }
  return env;
}

/** Wrap the raw spec body as the default export the harness imports. */
function wrapSpec(specSource: string): string {
  return [
    '// Auto-generated by Vyzus — user journey spec wrapped for the sandbox.',
    'export default async ({ page, context, expect }) => {',
    specSource,
    '};',
    '',
  ].join('\n');
}

export async function runInSandbox(input: SandboxInput): Promise<SandboxOutcome> {
  const harnessPath = resolveHarnessPath();
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vyzus-journey-'));
  const specPath = path.join(tempDir, 'spec.mjs');
  const configPath = path.join(tempDir, 'config.json');

  const config: HarnessConfig = {
    specPath,
    artifactsDir: input.artifactsDir,
    timeoutMs: input.timeoutMs,
  };

  await fs.writeFile(specPath, wrapSpec(input.specSource), 'utf8');
  await fs.writeFile(configPath, JSON.stringify(config), 'utf8');

  const startedAt = Date.now();
  try {
    return await new Promise<SandboxOutcome>((resolve) => {
      const child = spawn(process.execPath, [harnessPath, configPath], {
        env: cleanChildEnv(),
        cwd: tempDir,
        stdio: ['ignore', 'pipe', 'pipe'],
      });

      let stdoutBytes = 0;
      let tail = ''; // rolling buffer — the result line arrives last
      let stderrTail = '';
      let hardKilled = false;
      let capExceeded = false;
      let settled = false;

      const finish = (outcome: SandboxOutcome): void => {
        if (settled) return;
        settled = true;
        clearTimeout(killTimer);
        resolve(outcome);
      };

      const killTimer = setTimeout(() => {
        hardKilled = true;
        child.kill('SIGKILL');
      }, input.timeoutMs + HARD_KILL_GRACE_MS);

      child.stdout.on('data', (chunk: Buffer) => {
        stdoutBytes += chunk.length;
        if (stdoutBytes > STDOUT_CAP_BYTES) {
          capExceeded = true;
          child.kill('SIGKILL');
          return;
        }
        tail = (tail + chunk.toString('utf8')).slice(-64 * 1024);
      });
      child.stderr.on('data', (chunk: Buffer) => {
        stderrTail = (stderrTail + chunk.toString('utf8')).slice(-8 * 1024);
      });

      child.on('error', (err) => {
        finish({
          status: 'error',
          durationMs: Date.now() - startedAt,
          errorMessage: `sandbox spawn failed: ${err.message}`,
          screenshotSaved: false,
          traceSaved: false,
          hardKilled: false,
        });
      });

      child.on('close', () => {
        const durationMs = Date.now() - startedAt;
        if (capExceeded) {
          finish({
            status: 'error',
            durationMs,
            errorMessage: `Spec exceeded the ${STDOUT_CAP_BYTES / (1024 * 1024)} MB stdout limit`,
            screenshotSaved: false,
            traceSaved: false,
            hardKilled: true,
          });
          return;
        }
        // Find the marked result line (scan from the end).
        const lines = tail.split('\n');
        for (let i = lines.length - 1; i >= 0; i--) {
          const line = lines[i];
          if (line && line.startsWith(RESULT_MARKER)) {
            try {
              const parsed = JSON.parse(line.slice(RESULT_MARKER.length)) as HarnessResult;
              finish({ ...parsed, hardKilled });
              return;
            } catch {
              break;
            }
          }
        }
        if (hardKilled) {
          finish({
            status: 'timeout',
            durationMs,
            errorMessage: `Journey hard-killed after exceeding ${input.timeoutMs} ms (unresponsive spec)`,
            screenshotSaved: false,
            traceSaved: false,
            hardKilled: true,
          });
        } else {
          finish({
            status: 'error',
            durationMs,
            errorMessage: `Sandbox exited without a result${stderrTail ? `; stderr: ${stderrTail.slice(0, 2000)}` : ''}`,
            screenshotSaved: false,
            traceSaved: false,
            hardKilled: false,
          });
        }
      });
    });
  } finally {
    await fs.rm(tempDir, { recursive: true, force: true }).catch(() => undefined);
  }
}
